apiVersion: v1
kind: Service
metadata:
  name: srdoc-api-service
spec:
  type: LoadBalancer
  selector:
    app: srdoc-api
  ports:
    - protocol: TCP
      port: 80        # Porta externa (IP p√∫blico)
      targetPort: 8080 # Porta interna do container (.NET)
