apiVersion: apps/v1
kind: Deployment
metadata:
  name: srdoc-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srdoc-api
  template:
    metadata:
      labels:
        app: srdoc-api
    spec:
      containers:
      - name: srdoc-api
        image: #{ACR_NAME}#.azurecr.io/srdoc-api:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: srdoc-secrets
              key: db-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: srdoc-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: srdoc-api