name: Build and Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: srdoc.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image to ACR
      run: |
        docker build \
          -t srdoc.azurecr.io/srdoc-api:${{ github.sha }} \
          -f SrDoc.Api/Dockerfile \
          SrDoc.Api
        docker push srdoc.azurecr.io/srdoc-api:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: srdoc
        cluster-name: aks-srdoc

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          backend/manifests/deployment.yaml
          backend/manifests/service.yaml
        images: |
          srdoc.azurecr.io/srdoc-api:${{ github.sha }}
